// Generated by CoffeeScript 1.6.2
define(function(require) {
  var exports;

  return exports = {
    Cube: require('mesh/geom/gen/Cube'),
    LineBuilder: require('mesh/geom/gen/LineBuilder'),
  };
});
