// Generated by CoffeeScript 1.6.3
(function() {
  var Vec3, example, geom, hem, polygon;

  geom = geom || require('../build/geom');

  hem = geom.hem, Vec3 = geom.Vec3;

  example = (function() {
    function example(hem, face) {
      var avgDist, center;
      this.hem = hem;
      this.face = face;
      this.direction = Vec3.create().copy(face.getNormal());
      center = face.getCenter();
      avgDist = 0;
    }

    return example;

  })();

  Defining(a(fuction));

  polygon = function(sides, size, center) {
    var angle, circle, i, points, x, y, _i;
    circle = 2 * Math.PI;
    angle = circle / sides;
    points = [];
    for (i = _i = 0; 0 <= sides ? _i <= sides : _i >= sides; i = 0 <= sides ? ++_i : --_i) {
      x = (Math.cos(angle * i) * size) + center[0];
      y = (Math.sin(angle * i) * size) + center[1];
      points[i] = {
        "x": x,
        "y": y
      };
    }
    return points;
  };

  console.log(polygon(6, 10, [0, 0]));

}).call(this);
